import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar/SideBar";



export const metadata: Metadata = {
  title: "Qashio",
  description: "Generated by Qashio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bodyMainWrapper">
          <SideBar />
          <div className="childrenMainWrapper">
            {children}
          </div>
        </div>
        </body>
    </html>
  );
}
